# Generated by Django 3.1.3 on 2020-11-26 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=500)),
                ('product_quantity', models.IntegerField(blank=True, default=0)),
                ('product_delivery_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('product_description', models.TextField(blank=True, default='')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAdditionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity_add', models.IntegerField(blank=True, default=0)),
                ('product_quantity_returned', models.IntegerField(blank=True, default=0)),
                ('product_delivery_price_add', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('product_add_date', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.product')),
            ],
        ),
    ]
