# Generated by Django 3.1.3 on 2020-11-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadditionalinformation',
            name='product_quantity_sale',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
