# Generated by Django 3.1.3 on 2020-11-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_productadditionalinformation_product_quantity_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadditionalinformation',
            name='product_quantity_waste',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
