# Generated by Django 3.1.3 on 2020-11-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_productadditionalinformation_product_quantity_waste'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadditionalinformation',
            name='document',
            field=models.TextField(blank=True, default=''),
        ),
    ]
