# Generated by Django 3.1.3 on 2020-11-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_productadditionalinformation_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productadditionalinformation',
            name='document',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
