# Generated by Django 3.1.3 on 2020-11-28 18:05

from django.db import migrations, models
import warehouse.validators


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20201128_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadditionalinformation',
            name='product_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productadditionalinformation',
            name='product_delivery_price_add',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[warehouse.validators.positive_number]),
        ),
        migrations.AlterField(
            model_name='productadditionalinformation',
            name='product_quantity_add',
            field=models.IntegerField(blank=True, default=0, validators=[warehouse.validators.positive_number]),
        ),
        migrations.AlterField(
            model_name='productadditionalinformation',
            name='product_quantity_returned',
            field=models.IntegerField(blank=True, default=0, validators=[warehouse.validators.positive_number]),
        ),
        migrations.AlterField(
            model_name='productadditionalinformation',
            name='product_quantity_sale',
            field=models.IntegerField(blank=True, default=0, validators=[warehouse.validators.positive_number]),
        ),
        migrations.AlterField(
            model_name='productadditionalinformation',
            name='product_quantity_waste',
            field=models.IntegerField(blank=True, default=0, validators=[warehouse.validators.positive_number]),
        ),
    ]
