# Generated by Django 3.1.3 on 2020-12-12 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_auto_20201211_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productadditionalinformation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productadditionalinformation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='warehouse.product'),
        ),
    ]
