# Generated by Django 3.1.3 on 2020-12-12 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_auto_20201213_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productadditionalinformation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product'),
        ),
    ]
