# Generated by Django 3.1.3 on 2020-12-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(auto_created=True, blank=True, upload_to='users'),
        ),
    ]
